name: despliega a Azure

on: [push]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: probando
      run: echo ${{ secrets.USERNAME }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: tarea-azure-rsync/
        remote_path: ${{ secrets.PATH }}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USER }}
        remote_key: ${{ secrets.KEY }}