name: despliega a Azure

on: [push]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: probando
      run: echo ${{ secrets.USER }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: up9cloud/action-rsync@master
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TARGET: /home/PabloVM
        ARGS_MORE: --no-perms -u